#!/usr/bin/env python3
"""Builds Sources/GamePresentation/CountryBorders.swift (decision 154).

Reads Natural Earth's 1:50m admin-0 countries (public domain), keeps the
countries whose public holidays the game has (GameCore's HolidayCalendar),
simplifies each ring (Douglas-Peucker), rounds it to thousandths of a degree
and writes it as zig-zag varint deltas in base64, one string per country.

Usage (README.md has the download):
    python3 -I tools/country-borders/build_country_borders.py \
        ne_50m_admin_0_countries.geojson Sources/GamePresentation/CountryBorders.swift
"""
import base64
import json
import sys

COUNTRIES = "AE AU BR CA CN DE FR GB HK ID IN JP KR MX NL NZ PL SA SG TH TW US VN ZA".split()
TOLERANCE = 0.01  # degrees, about a kilometre
SCALE = 1000      # thousandths of a degree


def code_of(properties):
    for key in ("ISO_A2_EH", "ISO_A2"):
        value = properties.get(key)
        if value and value != "-99":
            return value
    return None


def simplify(points, tolerance):
    """Douglas-Peucker on a closed ring's points (the last equals the first)."""
    if len(points) < 4:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        first, last = stack.pop()
        (ax, ay), (bx, by) = points[first], points[last]
        dx, dy = bx - ax, by - ay
        length = dx * dx + dy * dy
        worst, index = -1.0, None
        for i in range(first + 1, last):
            px, py = points[i]
            if length == 0:
                distance = (px - ax) ** 2 + (py - ay) ** 2
            else:
                t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / length))
                distance = (px - ax - t * dx) ** 2 + (py - ay - t * dy) ** 2
            if distance > worst:
                worst, index = distance, i
        if index is not None and worst > tolerance * tolerance:
            keep[index] = True
            stack.append((first, index))
            stack.append((index, last))
    return [p for p, k in zip(points, keep) if k]


def varint(value, out):
    value = (value << 1) ^ (value >> 63)  # zig-zag
    value &= (1 << 64) - 1
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return


def encode(rings):
    """Each ring: its point count, then (longitude, latitude) deltas."""
    out = bytearray()
    varint(len(rings), out)
    for ring in rings:
        varint(len(ring), out)
        last = (0, 0)
        for lon, lat in ring:
            varint(lon - last[0], out)
            varint(lat - last[1], out)
            last = (lon, lat)
    return base64.b64encode(bytes(out)).decode()


def main(source, target):
    features = json.load(open(source, encoding="utf-8"))["features"]
    rings = {code: [] for code in COUNTRIES}
    for feature in features:
        code = code_of(feature["properties"])
        if code not in rings:
            continue
        geometry = feature["geometry"]
        polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
        for polygon in polygons:
            for ring in polygon:
                simple = simplify([tuple(p) for p in ring], TOLERANCE)
                rounded = []
                for lon, lat in simple[:-1]:
                    point = (round(lon * SCALE), round(lat * SCALE))
                    if not rounded or rounded[-1] != point:
                        rounded.append(point)
                if len(rounded) >= 3:
                    rings[code].append(rounded)
    missing = [code for code, found in rings.items() if not found]
    if missing:
        sys.exit(f"No border for {missing}")
    lines = [
        "// Generated by tools/country-borders/build_country_borders.py from Natural",
        "// Earth's 1:50m admin-0 countries (v5.1.2, public domain: \"Made with",
        "// Natural Earth\"). Do not edit: run the tool again (its README).",
        "//",
        "// Each country's rings, simplified to about a kilometre, in thousandths",
        "// of a degree: base64 of zig-zag varints, the ring count, then for each",
        "// ring its point count and its (longitude, latitude) deltas.",
        "",
        "extension CountryLookup {",
        "    static let encodedBorders: [String: String] = [",
    ]
    total = 0
    for code in COUNTRIES:
        total += sum(len(r) for r in rings[code])
        lines.append(f'        "{code}": "{encode(rings[code])}",')
    lines += ["    ]", "}", ""]
    open(target, "w", encoding="utf-8").write("\n".join(lines))
    print(f"{len(COUNTRIES)} countries, {total} points, {sum(len(l) for l in lines)} characters")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
